#!/bin/bash

REMOVE="remove-library"

if [ $1 = "make" ]; then

    ghc --make \
        -hidir website/ghc_output \
        -odir website/ghc_output \
        -o $REMOVE \
        -isrc \
        src/Registry/Remover.hs \
    && mv $REMOVE website/

else

    cd website/
    ./$REMOVE $1

fi
    
