#!/bin/bash

SERVE="public-library"

if [ $1 = "make" ]; then

    ghc --make \
        -O2 \
        -threaded \
        -hidir website/ghc_output \
        -odir website/ghc_output \
        -o $SERVE \
        -isrc \
        src/Registry/Server.hs \
    && mv $SERVE website/

elif [ $1 = "start" ]; then

    pkill $SERVE
    cd website/
    ./$SERVE &

elif [ $1 = "stop" ]; then

    pkill $SERVE

fi
    