#!/bin/bash

SERVE="public-library"

if [ $1 = "make" ]; then

    ghc --make -O2 -threaded -hidir ghc_output -odir ghc_output Registry/Server.hs -o $SERVE

elif [ $1 = "start" ]; then

    pkill $SERVE
    ./$SERVE &

elif [ $1 = "stop" ]; then

    pkill $SERVE

fi
    